### ISSUE TITLE
iOS: importing Account Tree seemingly fails

### ISSUE THREAD

**Issue by cristarta** [nicktylah/gnucash-mobile#7]
Hi there,

Just installed the app on an iOS device and have run into an issue when importing the Account Tree.

I exported the Account Tree from gnuCash using the `.csv` extension as outlined in the instructions (with and without quotes) but the app import process does not seem to work.

The import of the `.csv` file results in a big grey panel and the `+` icon popping up in the bottom right. It seems to be failing somewhere but I do not understand why - or how to go about troubleshooting. Is there something else that should be modified in the exported file for it to work?

Cheers

**Comment by nicktylah** [comment]
Heya, thanks for the report. Any chance you could upload the offending account tree or a redacted version of it with personal information removed? I haven't been able to replicate this on my end.

**Comment by Beakerboy** [comment]
i thought I'd mention that account tree imported perfectly fine for me. Version 1.0.5, Exported from an old version...OsX build of Version: 3.2

**Comment by cristarta** [comment]
Hi, apologies for the delay on my end.

I attempted to export from GnuCash (Windows v. 4.8, build 4.8a+(2021-09-28)) using the following steps: **File** -> **Export** -> **Export Account Tree to CSV**

Export Settings: **Separators: Comma (,)**

Importing account tree on iOS 12 and 15 both go through on the devices, grey panel appears and a simple transaction can be added (amount and description).

However the main issue remains: There does not seem to be any account tree displayed or the ability to assign transactions to subaccounts.

I've uploaded a blank testing book that I recently tested again on an iOS 15 device:

- [testbook.zip](https://github.com/nicktylah/gnucash-mobile/files/7920606/testbook.zip)

Would you happen to have a known working structure I may test with on my end?

**Comment by Beakerboy** [comment]
For me, after importing a tree the app will open listing the top level accounts (Asset, Liability, etc.). In order to add a transaction to an account I have to browse to that account and then press the “+”. If I press it on the main menu without browsing to a subaccount all I can enter is the amount and description with no option for the credit and debit account, date, or notes.

once I add one of these ‘root level’ transactions, I am unable to see the account tree, and the only way to recover is to remove all transactions.
